### ISSUE TITLE
How to test the main function of pitch?

### ISSUE THREAD

**Issue by ucasiggcas** [BrianMargolis/EECS-352-Project#1]
Dear,
Thanks to your great project,
Now I just want to test the pitch of Piano,no matter what Note Name.
Could it be possible?
Thx

**Comment by ucasiggcas** [comment]
In the [file](https://github.com/BrianMargolis/HapTuner/blob/master/HapTuner/HapTuner.ino)
there is not Audio.h,no Wire.h,No SPI.h,No SD.h No SerialFlash.h
Where can I find them?

**Comment by BrianMargolis** [comment]
I'm not sure what your original question is asking, but the reason all those .h files are missing is that they're Arduino built-ins.

**Comment by BrianMargolis** [comment]
I've received no follow-up on this in over a week, so I'm closing the issue.
